### ISSUE TITLE
Doesn't seem to work with 3.5.0.GA?

### ISSUE THREAD

**Issue by jamessugrue** [Px-Factor/titanium-installreferrer#1]
Hi 

I tested out your module in a new project using 3.5.0.GA but it doesn't seem to work. Have you tried it with newer versions of Titanium? Are you sure that there is no need to add anything more in the tiapp.xml? 

Thanks

**Comment by Px-Factor** [comment]
No, I haven't tested it yet, but will try to do it today and report back.

**Comment by jamessugrue** [comment]
Thanks! I appreciate it.

**Comment by Px-Factor** [comment]
Just tested it with 3.5.0.GA, and it did work. 
Basically, the only thing that needs to be added to your tiapp.xml is `<module platform="android">net.pixelfactor.installreferrer</module>` which is generated if you add the module in the tiapp.xml GUI editor. Everything else is being taken care of by the module.

Could you please post the tiaapp.xml and AndroidManifest.xml (found under build/android folder) so I can see if there's a problem there?

**Comment by jamessugrue** [comment]
Thanks 

Here's my AndroidManifest.xml 

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="yo.android" android:versionCode="1" android:versionName="1.0">
    <uses-sdk android:minSdkVersion="10" android:targetSdkVersion="19"/>
    <application android:icon="@drawable/appicon" android:label="YoAndroid" android:name="YoandroidApplication" android:debuggable="false" android:theme="@style/Theme.AppCompat">
        <activity android:name=".YoandroidActivity" android:label="@string/app_name" android:theme="@style/Theme.Titanium" android:configChanges="keyboardHidden|orientation|screenSize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:name="org.appcelerator.titanium.TiActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
        <activity android:name="org.appcelerator.titanium.TiTranslucentActivity" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@style/Theme.AppCompat.Translucent"/>
        <activity android:name="ti.modules.titanium.ui.android.TiPreferencesActivity" android:configChanges="screenSize"/>
        <service android:name="com.appcelerator.analytics.APSAnalyticsService" android:exported="false"/>
        <receiver android:exported="true" android:name="net.pixelfactor.installreferrer.ReferrerBroadcastReceiver">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER"/>
            </intent-filter>
        </receiver>
    </application>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
</manifest>
```

And here's my tiapp.xml (the Android section)

``` xml
   <android xmlns:android="http://schemas.android.com/apk/res/android">
        <application android:debuggable="false"
            android:hardwareAccelerated="true" android:largeHeap="true">
        </application>
    </android>
    <mobileweb>
        <precache/>
        <splash>
            <enabled>true</enabled>
            <inline-css-images>true</inline-css-images>
        </splash>
        <theme>default</theme>
    </mobileweb>
    <modules>
        <module platform="android">net.pixelfactor.installreferrer</module>
    </modules>
    <deployment-targets>
        <target device="android">true</target>
        <target device="blackberry">false</target>
        <target device="ipad">false</target>
        <target device="iphone">false</target>
        <target device="mobileweb">false</target>
    </deployment-targets>
    <sdk-version>3.5.0.GA</sdk-version>
    <plugins>
        <plugin version="1.0">ti.alloy</plugin>
    </plugins>
</ti:app>
```

**Comment by Px-Factor** [comment]
Umm, both look OK. When you say that it doesn't seem to work, do you mean that if you add the following code, it returns null?

```
var installReferrer = require('net.pixelfactor.installreferrer');
var utmSource = decodeURIComponent(installReferrer.getUtmSource());
console.log(utmSource);
```

**Comment by jamessugrue** [comment]
Exactly - it returns null.
I tried using the following command to test it out.

adb shell am broadcast -a com.android.vending.INSTALL_REFERRER —es
"referrer" "__y%3D1%26__ysurl%3Dmb.c.d%26utm_source%3Dtest_source"

**Comment by Px-Factor** [comment]
I think the problem is with the —es, which should be --es. I ran the following in terminal:

```
./adb shell am broadcast -a com.android.vending.INSTALL_REFERRER --es "referrer" "__y%3D1%26__ysurl%3Dmb.c.d%26utm_source%3Dtest_source"
```

and got the following:

```
Broadcasting: Intent { act=com.android.vending.INSTALL_REFERRER (has extras) }
```

And after a few more seconds:

```
Broadcast completed: result=-1
```

And the console in Titanium Studio then showed:

```
[INFO] :   I/net.pixelfactor.installreferrer: Received INSTALL_REFERRER URI: __y%253D1%2526__ysurl%253Dmb.c.d%2526utm_source%253Dtest_source
```

If you get this far and have the code from my previous post in your project, then the next time you run the app you should see*:

```
[INFO] :   utm_source%3Dtest_utm_source%26utm_medium%3Dutm_test_medium
```

Could you try this please and let me know?
- In "real life" the intent is being broadcasted right after the app has finished installing, so the URL should be available the first time you run the app, and it is stored for eternity -- or until the user removes it.

**Comment by jamessugrue** [comment]
Cool - I'll try that out now

Also, just wondering, could you share a project that uses your module as a sample?

**Comment by jamessugrue** [comment]
Great! That worked thanks.

**Comment by Px-Factor** [comment]
Great! I will post a sample project when I get the time (and if I don't forget).

**Comment by jamessugrue** [comment]
I'll give you my sample project later, if that helps

**Comment by Px-Factor** [comment]
I have edited README.md to add details on testing with through terminal, and added sample code in example/app.js.
I think this should be enough to get people going with the module, but if you want to add a sample project, I'll add it to the repository.

**Comment by AlokGupta007** [comment]
on first lunch after instal, it is not worked with 
https://play.google.com/store/apps/details?id=com.jawabkom.inappTest&referrer=helloAlok.
using titanium 5.3.0 sdk..
using correct terminal command.
