### ISSUE TITLE
Referral code on first launch the app after install not in single time

### ISSUE THREAD

**Issue by AlokGupta007** [Px-Factor/titanium-installreferrer#2]
Hello Team , This module is not working in first lunch after install. Not able to get the referral code. I am using titanium 5.3.0 sdk. Please help

**Comment by Px-Factor** [comment]
Hi,
Could you please copy your tiapp.xml file and the code you are using to implement this module?

**Comment by AlokGupta007** [comment]
here is the android section of tiapp.xml

<android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest android:versionCode="51" android:versionName="1.0">
            <application android:debuggable="false"
                android:icon="@drawable/appicon"
                android:label="Jawabkom" android:largeHeap="true"
                android:name="JawabkomApplication" android:theme="@style/Theme.NoActionBar">
                <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="23"/>
                <uses-permission android:name="com.android.vending.BILLING"/>
                <activity
                    android:configChanges="keyboardHidden|orientation|screenSize"
                    android:label="Jawabkom"
                    android:name=".JawabkomActivity" android:screenOrientation="portrait">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN"/>
                        <category android:name="android.intent.category.LAUNCHER"/>
                    </intent-filter>
                </activity>
                <activity
                    android:configChanges="keyboardHidden|orientation|screenSize"
                    android:label="Jawabkom"
                    android:name="com.jawabkom.inappTest" android:screenOrientation="portrait">
                    <intent-filter android:label="Jawabkom">
                        <action android:name="android.intent.action.VIEW"/>
                        <category android:name="android.intent.category.DEFAULT"/>
                        <category android:name="android.intent.category.BROWSABLE"/>
                        <data android:host="myapp" android:scheme="jawabkom"/>
                    </intent-filter>
                </activity>
            </application>
        </manifest>
    </android>

<modules>  
        <module platform="android">net.pixelfactor.installreferrer</module>  
    </modules>
<sdk-version>5.3.0.GA</sdk-version>

var installReferrer = require('net.pixelfactor.installreferrer');
var args = decodeURIComponent(installReferrer.getUtmSource());

**Comment by Px-Factor** [comment]
From what I can see it looks OK. Have you tried testing it with the following command:

`./adb shell am broadcast -a com.android.vending.INSTALL_REFERRER --es "referrer" "utm_source%3Dtest_utm_source%26utm_medium%3Dutm_test_medium"`

or with the app I've linked in the description?

**Comment by Px-Factor** [comment]
I've just seen your comment on the closed issued... I think this might be to your URL, which should look like this:
[https://play.google.com/store/apps/details?id=com.jawabkom.inappTest&referrer=utm_source%3DhelloAlok](https://play.google.com/store/apps/details?id=com.jawabkom.inappTest&referrer=utm_source%3DhelloAlok)

You can check out [https://developers.google.com/analytics/devguides/collection/android/v4/campaigns#campaign-params](https://developers.google.com/analytics/devguides/collection/android/v4/campaigns#campaign-params) which has a URL builder

**Comment by AlokGupta007** [comment]
thanks for the response, the second link is not found. I have tried with the link what you suggest but not getting the referral code in first lunch. Please help. It's urgent. you check directly with link. you will show the alert. I am printing the code in alert.

**Comment by Px-Factor** [comment]
Hi,
1. I've fixed the URLs above.
2. I used this link [https://play.google.com/store/apps/details?id=com.jawabkom.inappTest&referrer=utm_source%3Dpxfactor%26utm_medium%3Dpxmedium](https://play.google.com/store/apps/details?id=com.jawabkom.inappTest&referrer=utm_source%3Dpxfactor%26utm_medium%3Dpxmedium), which I created with the URL builder in my previous post to install your app. On first run, I did receive Null in the alert, but on second run it did show the URL referrer. Here is a screenshot:
   ![utm](https://cloud.githubusercontent.com/assets/2623283/16070350/f319af5e-32d4-11e6-94bf-fd135ce2a9e8.jpeg)
3. The reason that it's not showing on first run is that the install referrer is received by an event sent by the OS, and it doesn't always (or rather, almost never) fires immediately when the app is started for the first time. So, you either have put the code in a setTimeout function, or rely on it the second time it runs.

**Comment by AlokGupta007** [comment]
Can we have another solution without? If launch second time then it does not retrieve the code returning null.

**Comment by Px-Factor** [comment]
Without what?
I didn't make up how the install referrer on Android works, I've just implemented it for Titanium, and as the screenshot shows, if the URL that refers to the app on Google Play is constructed according to Google's requirements, the module works as intended.

**Comment by AlokGupta007** [comment]
No I am talking about the setTimeout function. It's never call for first time.

**Comment by AlokGupta007** [comment]
Even in single time it is not working.
